CrudAlunosSieg/Models/contexto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace CrudAlunosSieg.Models
{
    public class contexto: DbContext
    {
        public DbSet<pessoa>Pessoas { get; set; }
    }
}

CrudAlunosSieg/Models/pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CrudAlunosSieg.Models
{
    public class pessoa
    {


        [Key]
        public int id { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public int idade { get; set; }
    }
}

CrudAlunosSieg/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrudAlunosSieg.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CrudAlunosSieg/Controllers/pessoasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CrudAlunosSieg.Models;

namespace CrudAlunosSieg.Controllers
{
    public class pessoasController : Controller
    {
        private contexto db = new contexto();

        // GET: pessoas
        public ActionResult Index()
        {
            return View(db.Pessoas.ToList());
        }

        // GET: pessoas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pessoa pessoa = db.Pessoas.Find(id);
            if (pessoa == null)
            {
                return HttpNotFound();
            }
            return View(pessoa);
        }

        // GET: pessoas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: pessoas/Create
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nome,cpf,idade")] pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                db.Pessoas.Add(pessoa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }else if (pessoa.cpf.Length != 11 || pessoa.nome == "")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(pessoa);
        }

        // GET: pessoas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pessoa pessoa = db.Pessoas.Find(id);
            if (pessoa == null)
            {
                return HttpNotFound();
            }
            return View(pessoa);
        }

        // POST: pessoas/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nome,cpf,idade")] pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pessoa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pessoa);
        }

        // GET: pessoas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pessoa pessoa = db.Pessoas.Find(id);
            if (pessoa == null)
            {
                return HttpNotFound();
            }
            return View(pessoa);
        }

        // POST: pessoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            pessoa pessoa = db.Pessoas.Find(id);
            db.Pessoas.Remove(pessoa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CrudAlunosSieg/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CrudAlunosSieg/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CrudAlunosSieg/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron" style="font-family: 'Poppins', sans-serif; background-color: #33cc95; text-align:center;">
    <h1 style="color: #f0f2f5;">Escola SIEG</h1>
    <p" class="lead">Nosso dever é te ver crescer</p>

</div>

<div class="row">
    <div class="col-md-4" style="margin: 1%; background-color: #33cc95; width: 30%; font-family: 'Poppins', sans-serif; font-size: 16px; ">
        <h2 style="color: #f0f2f5;">Princípios da escola:</h2>
        <p>
            Nossa escola foi fundada em 2022, a disciplina faz parte de um dos valores fundamentais para que o aluno se mantenha em nosso ambiente escolar. Acreditamos no poder da educação e na transformação que a mesma causa na vida das pessoas, por isso a escola SIEG está empenhada em ajudar seu filho no que ele precisar.
        </p>

    </div>
    <div class="col-md-4" style="margin: 1%; background-color: #33cc95; width: 30%; font-family: 'Poppins', sans-serif; font-size: 16px; ">
        <h2 style="color: #f0f2f5;">Metas do ano:</h2>
        <p>Implementar o programa Mais Bolsas, que consiste em 10 bolsas de estudos para pessoas carentes das periferias de Recife. </p>

    </div>
    <div class="col-md-4" style="margin: 1%; background-color: #33cc95; width: 30%; font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 16px;">
        <h2 style="color: #f0f2f5;">Conheça nossa escola:</h2>
        <p>Escola SIEG 2022</p>
        <p>Ir até o site: <a class="btn btn-default" href="https://pp.colegiomotivo.com.br/"   style="background-color: #6933FF; color: whitesmoke;">Acessar</a></p>
    </div>
</div>

CrudAlunosSieg/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="icon" href="faviconaluno.png" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">

    <title>@ViewBag.Title - Cadastro de Alunos SIEG 2022</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #6933FF; font-family: 'Poppins', sans-serif;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Registrar Aluno", "Index", "pessoas")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer  style="background-color: #6933FF">
            <p style="color: whitesmoke; font-family: 'Poppins', sans-serif;">&copy; @DateTime.Now.Year - Cadastro de alunos SIEG</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CrudAlunosSieg/Views/pessoas/Create.cshtml
@model CrudAlunosSieg.Models.pessoa

@{
    ViewBag.Title = "Create";
}

<h2 style="font-family: 'Poppins', sans-serif;">Criar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 style="font-family: 'Poppins', sans-serif;">Aluno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group"  >
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cpf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10"  >
                @Html.EditorFor(model => model.cpf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" >
            @Html.LabelFor(model => model.idade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" >
                @Html.EditorFor(model => model.idade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input style="font-family: 'Poppins', sans-serif; color: whitesmoke; background-color: #6933FF;" type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CrudAlunosSieg/Views/pessoas/Delete.cshtml
@model CrudAlunosSieg.Models.pessoa

@{
    ViewBag.Title = "Delete";
}

<h2 style="font-family: 'Poppins', sans-serif;">Deletar Aluno do cadastro</h2>

<h3 style="font-family: 'Poppins', sans-serif;">Tem certeza que deseja deletar o aluno?</h3>
<div>
    <h4 style="font-family: 'Poppins', sans-serif;">Aluno</h4>
    <hr />
    <dl class="dl-horizontal" style="font-family: 'Poppins', sans-serif;">
        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cpf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.idade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idade)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input  style="font-family: 'Poppins', sans-serif; color: whitesmoke; background-color: #6933FF;" type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

CrudAlunosSieg/Views/pessoas/Details.cshtml
@model CrudAlunosSieg.Models.pessoa

@{
    ViewBag.Title = "Details";
}

<h2  style="font-family: 'Poppins', sans-serif;">Detalhes</h2>

<div>
    <h4 style="font-family: 'Poppins', sans-serif;">Aluno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cpf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.idade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idade)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Voltar", "Index")
</p>

CrudAlunosSieg/Views/pessoas/Edit.cshtml
@model CrudAlunosSieg.Models.pessoa

@{
    ViewBag.Title = "Edit";
}

<h2 style="font-family: 'Poppins', sans-serif;">Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 style="font-family: 'Poppins', sans-serif;">Aluno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cpf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cpf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input style="font-family: 'Poppins', sans-serif; color: whitesmoke; background-color: #6933FF;" type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CrudAlunosSieg/Views/pessoas/Index.cshtml
@model IEnumerable<CrudAlunosSieg.Models.pessoa>

@{
    ViewBag.Title = "Index";
}
<div style="display: flex; align-items:center;">
    <h2>Cadastro de Alunos SIEG</h2>
    <img src="faviconaluno.png">
</div>

<p>
    @Html.ActionLink("Cadastrar Aluno", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cpf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idade)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cpf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.idade)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.id }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>